# Generated by Django 4.0.4 on 2022-06-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmid', models.IntegerField()),
                ('pmcid', models.IntegerField()),
                ('doi', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=4)),
                ('journal', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=200)),
                ('directness', models.CharField(choices=[('DIRECT', 'DIRECT'), ('INDIRECT', 'INDIRECT')], max_length=8)),
                ('mechanism', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
                ('species', models.CharField(max_length=100)),
                ('conclusions', models.TextField()),
                ('zebra', models.URLField()),
                ('sourcelink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genelist.literature')),
            ],
        ),
    ]
