# Generated by Django 4.0.4 on 2022-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='year',
        ),
    ]
