# Generated by Django 4.0.4 on 2022-07-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genelist', '0002_remove_literature_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='doi',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='literature',
            name='pmcid',
            field=models.CharField(max_length=10),
        ),
    ]
